import type { Metadata } from "next";
import { Geist, Geist_Mono,Anton, Open_Sans, Inter, Lato } from "next/font/google";
import "./globals.css";

const geistSans = Lato({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:"400"
});

const geistMono = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className}   antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
